Created eslint.yml file
ChrisKoetzee/EZ-It-Project pull request #30
Opened 2023-05-02 18:48 UTC by shafiekdavids

Created workflows folder under .github directory with the eslint.yml file inside

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

Write a summary of your change. Explain why you have made it.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-05-02 19:00 UTC, Craques requested changes

2023-05-02 19:00 UTC, Craques commented on .github/workflows/eslint.yml
> +  - production
Looks good, you may not need to specify branches here, you can just specify for it to run on pull_requests.
`on: [pull_request, workflow_dispatch]` for this on line 3, we may not have any of the branches you listed above

you can check more information https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

2023-05-03 14:16 UTC, textbook commented on client/eslintrc.yml
Note that the starter kit already has linting configuration (for both ESLint and Prettier) set up: https://github.com/search?q=user%3Acodeyourfuture+repo%3Acyf-final-project-starter-kit+path%3A**%2F.eslintrc.json&type=code&ref=advsearch. The CYF config already starts from `eslint:recommended` per https://github.com/CodeYourFuture/eslint-config-standard#rules.

2023-05-07 07:50 UTC, Craques approved these changes

2023-05-07 07:51 UTC, Craques commented
looks good, you may want to run the fix but this is the epected behaviour

2023-05-07 09:06 UTC, Craques commented on .github/workflows/eslint.yml
> +        run: npm run lint-and-format
The previous command was ok, you needed to fix the linting issues so that this would pass, we can have a 10 minute call sometime to finalise this

2023-05-08 19:21 UTC, Craques approved these changes

2023-05-08 19:23 UTC, ChrisKoetzee approved these changes

2023-05-08 19:23 UTC, ChrisKoetzee approved these changes

2023-05-08 19:25 UTC, merged