#20 student registration end point Chris Koetzee
ChrisKoetzee/EZ-It-Project pull request #34
Opened 2023-05-04 18:42 UTC by ChrisKoetzee

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

So the endpoints for students was created in a student file in the server folder and students was imported into the app.js folder where routes were created in so that there was no need to reuse in the student folder.  Also pool was already created in the db.js folder where we imported the query to reuse in the students folder.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [y ] My code follows the style guidelines of this project
- [y ] I have carefully reviewed my own code
- [y ] I have commented my code
- [y ] I have updated any documentation

2023-05-06 07:31 UTC, Craques requested changes

2023-05-06 07:31 UTC, Craques commented on server/student.js
> +		.catch((error) => res.status(500).json({error: 'Information loaded incorrectly - ' + error.message}));
Maybe you can use a 400 here as a 500 error is reserved for server crashes https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2023-05-06 10:40 UTC, Craques approved these changes

2023-05-07 17:34 UTC, shafiekdavids submitted a review, later dismissed
Looks good from what I can see

2023-05-08 17:27 UTC, Craques approved these changes

2023-05-09 18:51 UTC, shafiekdavids approved these changes
Looks good

2023-05-09 18:52 UTC, merged